Update usb-dirty-pages-udev

diff --git a/files/0-system/usr/bin/usb-dirty-pages-udev b/files/0-system/usr/bin/usb-dirty-pages-udev
--- a/files/0-system/usr/bin/usb-dirty-pages-udev
+++ b/files/0-system/usr/bin/usb-dirty-pages-udev
@@ -9,7 +9,14 @@ set -x
 # model id is passed as ${3}
 
 # Determine current USB device speed, as ATTRS{speed} is unreliable - it detects xHCI USB speed instead of proper USB speed
-current_usb_speed=$(lsusb -t -v | awk -v vendor_id="${2}" -v module_id="${3}" '$0 ~ vendor_id ":" module_id {split(prev, a, " "); print a[length(a)]} {prev=$0}' | sed -n 's/[^0-9]*\([0-9]*\(\.[0-9]*\)\?\).*/\1/p')
+current_usb_speed=$(lsusb -t -v | awk -v vendor_id="${2}" -v module_id="${3}" '$0 ~ vendor_id ":" module_id {split(prev, a, " "); print a[length(a)]} {prev=$0}' | grep -o '[0-9]*\.[0-9]*\|[0-9]*')
+
+# Handle the case if float is with , as decimal separator
+if [[ $(echo "${current_usb_speed}" | wc -l) -gt 1 ]]; then
+  echo "Cannot determine current USB speed for the device to write custom max_bytes dirty value"
+  echo "Exiting"
+  exit 1
+fi
 
 # If current USB speed is somehow not determined or wrongly parsed, then stop the script
 # if it's empty or if USB speed is not in integer or floats
